/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'service' : Service,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'preferredDateTime' : string,
  'notes' : [] | [string],
  'phone' : string,
}
export type BookingId = bigint;
export interface BookingSubmission {
  'service' : Service,
  'name' : string,
  'email' : string,
  'preferredDateTime' : string,
  'notes' : [] | [string],
  'phone' : string,
}
export type Service = { 'styling' : null } |
  { 'pedicure' : null } |
  { 'other' : string } |
  { 'treatment' : null } |
  { 'blowout' : null } |
  { 'haircut' : null } |
  { 'highlights' : null } |
  { 'coloring' : null } |
  { 'manicure' : null } |
  { 'facial' : null };
export type SubmitResult = { 'ok' : BookingId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'submitBooking' : ActorMethod<[BookingSubmission], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];