/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const Service = IDL.Variant({
  'styling' : IDL.Null,
  'pedicure' : IDL.Null,
  'other' : IDL.Text,
  'treatment' : IDL.Null,
  'blowout' : IDL.Null,
  'haircut' : IDL.Null,
  'highlights' : IDL.Null,
  'coloring' : IDL.Null,
  'manicure' : IDL.Null,
  'facial' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : BookingId,
  'service' : Service,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const BookingSubmission = IDL.Record({
  'service' : Service,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : BookingId, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func([BookingSubmission], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const Service = IDL.Variant({
    'styling' : IDL.Null,
    'pedicure' : IDL.Null,
    'other' : IDL.Text,
    'treatment' : IDL.Null,
    'blowout' : IDL.Null,
    'haircut' : IDL.Null,
    'highlights' : IDL.Null,
    'coloring' : IDL.Null,
    'manicure' : IDL.Null,
    'facial' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : BookingId,
    'service' : Service,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const BookingSubmission = IDL.Record({
    'service' : Service,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : BookingId, 'err' : IDL.Text });
  
  return IDL.Service({
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func([BookingSubmission], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };