/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookingSubmission {
    service: Service;
    name: string;
    email: string;
    preferredDateTime: string;
    notes?: string;
    phone: string;
}
export type SubmitResult = {
    __kind__: "ok";
    ok: BookingId;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export type Service = {
    __kind__: "styling";
    styling: null;
} | {
    __kind__: "pedicure";
    pedicure: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "treatment";
    treatment: null;
} | {
    __kind__: "blowout";
    blowout: null;
} | {
    __kind__: "haircut";
    haircut: null;
} | {
    __kind__: "highlights";
    highlights: null;
} | {
    __kind__: "coloring";
    coloring: null;
} | {
    __kind__: "manicure";
    manicure: null;
} | {
    __kind__: "facial";
    facial: null;
};
export type BookingId = bigint;
export interface Booking {
    id: BookingId;
    service: Service;
    name: string;
    submittedAt: Timestamp;
    email: string;
    preferredDateTime: string;
    notes?: string;
    phone: string;
}
export interface backendInterface {
    listBookings(): Promise<Array<Booking>>;
    submitBooking(submission: BookingSubmission): Promise<SubmitResult>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingSubmission as _BookingSubmission, Service as _Service, SubmitResult as _SubmitResult, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async listBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBooking(arg0: BookingSubmission): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_BookingSubmission_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubmitResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_BookingSubmission_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubmitResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    service: _Service;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    preferredDateTime: string;
    notes: [] | [string];
    phone: string;
}): {
    id: BookingId;
    service: Service;
    name: string;
    submittedAt: Timestamp;
    email: string;
    preferredDateTime: string;
    notes?: string;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_Service_n4(_uploadFile, _downloadFile, value.service),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        preferredDateTime: value.preferredDateTime,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        phone: value.phone
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookingId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    styling: null;
} | {
    pedicure: null;
} | {
    other: string;
} | {
    treatment: null;
} | {
    blowout: null;
} | {
    haircut: null;
} | {
    highlights: null;
} | {
    coloring: null;
} | {
    manicure: null;
} | {
    facial: null;
}): {
    __kind__: "styling";
    styling: null;
} | {
    __kind__: "pedicure";
    pedicure: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "treatment";
    treatment: null;
} | {
    __kind__: "blowout";
    blowout: null;
} | {
    __kind__: "haircut";
    haircut: null;
} | {
    __kind__: "highlights";
    highlights: null;
} | {
    __kind__: "coloring";
    coloring: null;
} | {
    __kind__: "manicure";
    manicure: null;
} | {
    __kind__: "facial";
    facial: null;
} {
    return "styling" in value ? {
        __kind__: "styling",
        styling: value.styling
    } : "pedicure" in value ? {
        __kind__: "pedicure",
        pedicure: value.pedicure
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "treatment" in value ? {
        __kind__: "treatment",
        treatment: value.treatment
    } : "blowout" in value ? {
        __kind__: "blowout",
        blowout: value.blowout
    } : "haircut" in value ? {
        __kind__: "haircut",
        haircut: value.haircut
    } : "highlights" in value ? {
        __kind__: "highlights",
        highlights: value.highlights
    } : "coloring" in value ? {
        __kind__: "coloring",
        coloring: value.coloring
    } : "manicure" in value ? {
        __kind__: "manicure",
        manicure: value.manicure
    } : "facial" in value ? {
        __kind__: "facial",
        facial: value.facial
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
function to_candid_BookingSubmission_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingSubmission): _BookingSubmission {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: Service;
    name: string;
    email: string;
    preferredDateTime: string;
    notes?: string;
    phone: string;
}): {
    service: _Service;
    name: string;
    email: string;
    preferredDateTime: string;
    notes: [] | [string];
    phone: string;
} {
    return {
        service: to_candid_Service_n9(_uploadFile, _downloadFile, value.service),
        name: value.name,
        email: value.email,
        preferredDateTime: value.preferredDateTime,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "styling";
    styling: null;
} | {
    __kind__: "pedicure";
    pedicure: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "treatment";
    treatment: null;
} | {
    __kind__: "blowout";
    blowout: null;
} | {
    __kind__: "haircut";
    haircut: null;
} | {
    __kind__: "highlights";
    highlights: null;
} | {
    __kind__: "coloring";
    coloring: null;
} | {
    __kind__: "manicure";
    manicure: null;
} | {
    __kind__: "facial";
    facial: null;
}): {
    styling: null;
} | {
    pedicure: null;
} | {
    other: string;
} | {
    treatment: null;
} | {
    blowout: null;
} | {
    haircut: null;
} | {
    highlights: null;
} | {
    coloring: null;
} | {
    manicure: null;
} | {
    facial: null;
} {
    return value.__kind__ === "styling" ? {
        styling: value.styling
    } : value.__kind__ === "pedicure" ? {
        pedicure: value.pedicure
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "treatment" ? {
        treatment: value.treatment
    } : value.__kind__ === "blowout" ? {
        blowout: value.blowout
    } : value.__kind__ === "haircut" ? {
        haircut: value.haircut
    } : value.__kind__ === "highlights" ? {
        highlights: value.highlights
    } : value.__kind__ === "coloring" ? {
        coloring: value.coloring
    } : value.__kind__ === "manicure" ? {
        manicure: value.manicure
    } : value.__kind__ === "facial" ? {
        facial: value.facial
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
